version: 2
jobs:
  deploy_internal_staging:
    docker:
      - image: circleci/node:10.10
    steps:
      - checkout
      - run:
          name: Installing all dependencies
          command: yarn install --ignore-engines
      - run:
          name: Build and deploy to internal staging
          command: |
            yarn build
            yarn deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy_internal_staging:
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
